from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml


def _upstream_url(upstream: dict[str, Any]) -> str:
    protocol = upstream.get("protocol", "http")
    node = _upstream_nodes(upstream)[0]
    return f"{protocol}://{node['host']}:{node['port']}"


def _upstream_nodes(upstream: dict[str, Any]) -> list[dict[str, Any]]:
    nodes = upstream.get("nodes")
    if nodes:
        return nodes
    return [{"host": upstream["host"], "port": upstream["port"], "weight": 100}]


def _kong_algorithm(name: str) -> str:
    return {
        "round-robin": "round-robin",
        "least-connections": "least-connections",
        "chash": "consistent-hashing",
    }[name]


def _write_yaml(path: Path, value: Any) -> None:
    path.write_text(yaml.safe_dump(value, sort_keys=False, allow_unicode=True), encoding="utf-8")


def _write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _render_caddy(manifest: dict[str, Any]) -> tuple[dict[str, str], dict[str, Any]]:
    gateway = manifest["gateway"]
    direct = gateway.get("entry_mode", "gateway") == "direct-new-api"
    upstreams = {item["id"]: item for item in manifest["upstreams"]}
    if direct:
        routes_by_host: dict[str, set[str]] = {}
        for route in manifest["routes"]:
            for host in route["hosts"]:
                routes_by_host.setdefault(host, set()).add(route["upstream"])
        if any(len(ids) != 1 for ids in routes_by_host.values()):
            raise ValueError("direct-new-api Caddy mode requires one upstream per Host")
        targets = {
            host: _upstream_url(upstreams[next(iter(ids))])
            for host, ids in routes_by_host.items()
        }
        if not any(
            (host.startswith("ai.") or host == "ai-internal.onwalk.net")
            and next(iter(ids)) == "new-api"
            for host, ids in routes_by_host.items()
        ):
            raise ValueError("direct-new-api mode requires an ai.* Host routed to New API")
        mode_report = "direct-new-api"
    else:
        gateway_upstream_id = {
            "kong": "kong",
            "apisix": "apisix",
            "nginx": "nginx",
        }.get(gateway["adapter"])
        if gateway_upstream_id is None:
            raise ValueError(f"caddy adapter cannot target gateway adapter {gateway['adapter']!r}")
        try:
            upstream = upstreams[gateway_upstream_id]
        except KeyError as exc:
            raise ValueError(
                f"gateway adapter {gateway['adapter']!r} requires upstream {gateway_upstream_id!r}"
            ) from exc
        target = f"{upstream['host']}:{upstream['port']}"
        targets = {host: target for host in {h for r in manifest["routes"] for h in r["hosts"]}}
        mode_report = f"gateway:{gateway['adapter']}"
    blocks: list[str] = [
        "# Generated by gatewayctl. Do not add secrets here.",
        "# This fragment owns only AI Gateway hosts; existing Web SaaS routes remain separate.",
        "",
    ]
    for host in sorted(targets):
        blocks.append(f"{host} {{")
        blocks.append(f"    reverse_proxy {targets[host]}")
        blocks.append("}")
        blocks.append("")
    report = {
        "adapter": "caddy",
        "entry_mode": mode_report,
        "supported": ["automatic-tls", "host-routing", "reverse-proxy"],
        "not_managed": [
            "ip-allowlist",
            "tenant-auth",
            "rate-limiting",
            "provider-credentials",
            "oauth",
        ],
    }
    return {"Caddyfile.ai-gateway": "\n".join(blocks)}, report


def _kong_plugins(route: dict[str, Any], tenant: dict[str, Any]) -> list[dict[str, Any]]:
    plugins: list[dict[str, Any]] = []
    auth_mode = route["auth"]["mode"]
    if auth_mode == "new-api-token":
        # New API is the identity and quota source of truth. Normalize the
        # OpenAI/Anthropic SDK header variants, but never replace the user's
        # credential with a Kong bootstrap/shared key.
        plugins.append(
            {
                "name": "pre-function",
                "config": {
                    "access": [
                        "local auth = kong.request.get_header('authorization')\n"
                        "if not auth or auth == '' then\n"
                        "  local key = kong.request.get_header('x-api-key') or kong.request.get_header('apikey')\n"
                        "  if key and key ~= '' then\n"
                        "    auth = key:match('^[Bb]earer%s+') and key or ('Bearer ' .. key)\n"
                        "  end\n"
                        "end\n"
                        "if not auth or auth == '' then\n"
                        "  return kong.response.exit(401, { message = 'New API user token required' })\n"
                        "end\n"
                        "kong.service.request.set_header('Authorization', auth)\n"
                        "kong.service.request.clear_header('x-api-key')\n"
                        "kong.service.request.clear_header('apikey')\n"
                    ]
                },
            }
        )
    elif auth_mode == "key-auth":
        plugins.append({"name": "key-auth", "config": {"hide_credentials": True}})
    else:
        plugins.append({"name": "jwt"})
    if auth_mode != "new-api-token":
        plugins.append(
            {
                "name": "acl",
                "config": {"allow": [f"tenant:{tenant['id']}"], "hide_groups_header": True},
            }
        )
    if tenant.get("rate_limit_per_minute"):
        plugins.append(
            {
                "name": "rate-limiting",
                "config": {
                    "minute": tenant["rate_limit_per_minute"],
                    "policy": "local",
                    **({"limit_by": "ip"} if auth_mode == "new-api-token" else {}),
                },
            }
        )
    plugins.extend(
        [
            {"name": "correlation-id", "config": {"header_name": "X-Request-ID", "echo_downstream": True}},
        ]
    )
    audit_headers = [f"X-AI-Gateway-Route: {route['id']}"]
    if auth_mode != "new-api-token":
        audit_headers.append(f"X-AI-Gateway-Tenant: {tenant['id']}")
    plugins.append({"name": "request-transformer", "config": {"add": {"headers": audit_headers}}})
    return plugins


def _render_kong(manifest: dict[str, Any]) -> tuple[dict[str, str], dict[str, Any]]:
    upstreams = {item["id"]: item for item in manifest["upstreams"]}
    tenants = {item["id"]: item for item in manifest["tenants"]}
    referenced_upstreams = {route["upstream"] for route in manifest["routes"]}
    services = []
    kong_upstreams = []
    for upstream in manifest["upstreams"]:
        if upstream["id"] not in referenced_upstreams:
            continue
        nodes = _upstream_nodes(upstream)
        if len(nodes) == 1 and "nodes" not in upstream:
            services.append({"name": upstream["id"], "url": _upstream_url(upstream)})
        else:
            schedule = upstream.get("schedule", {})
            services.append(
                {
                    "name": upstream["id"],
                    "protocol": upstream.get("protocol", "http"),
                    "host": upstream["id"],
                    "port": 80,
                    **{
                        key: schedule[f"{key}_ms"]
                        for key in ("connect_timeout", "read_timeout", "write_timeout")
                        if f"{key}_ms" in schedule
                    },
                }
            )
            kong_upstreams.append(
                {
                    "name": upstream["id"],
                    "algorithm": _kong_algorithm(schedule.get("algorithm", "round-robin")),
                    "targets": [
                        {
                            "target": f"{node['host']}:{node['port']}",
                            "weight": node.get("weight", 100),
                        }
                        for node in nodes
                    ],
                }
            )

    routes = []
    for route in manifest["routes"]:
        tenant = tenants[route["tenant_ref"]]
        if not tenant["enabled"]:
            continue
        routes.append(
            {
                "name": route["id"],
                "hosts": route["hosts"],
                "paths": route["paths"],
                "strip_path": False,
                "protocols": ["http", "https"],
                "service": {"name": route["upstream"]},
                "plugins": _kong_plugins(route, tenant),
            }
        )

    consumers = [
        {
            "username": tenant["id"],
            "groups": [{"name": f"tenant:{tenant['id']}"}],
            "tags": ["ai-gateway", "declarative-contract"],
        }
        for tenant in manifest["tenants"]
    ]
    bundle = {
        "_format_version": "3.0",
        "_transform": True,
        "upstreams": kong_upstreams,
        "services": services,
        "routes": routes,
        "consumers": consumers,
    }
    report = {
        "adapter": "kong",
        "mode": "traditional",
        "runtime_config_backend": "postgresql",
        "supported": ["jwt", "key-auth", "acl", "rate-limiting", "correlation-id", "audit-metadata"],
        "scheduling": ["round-robin", "least-connections", "chash", "weighted-targets", "timeouts"],
        "requires_runtime_credentials": True,
        "requires_external_sync": "admin-api-or-deck",
        "not_managed": ["database-dsn", "client-credential-values", "provider-api-keys", "oauth"],
        "upstreams": sorted(upstreams),
    }
    return {"kong.yaml": yaml.safe_dump(bundle, sort_keys=False, allow_unicode=True)}, report


def _render_apisix(manifest: dict[str, Any]) -> tuple[dict[str, str], dict[str, Any]]:
    referenced_upstreams = {route["upstream"] for route in manifest["routes"]}
    upstreams = {
        item["id"]: item
        for item in manifest["upstreams"]
        if item["id"] in referenced_upstreams
    }
    tenants = {item["id"]: item for item in manifest["tenants"]}
    upstream_items = []
    for index, upstream in enumerate(upstreams.values(), start=1):
        schedule = upstream.get("schedule", {})
        upstream_item = {
            "id": index,
            "name": upstream["id"],
            "type": "roundrobin",
            "nodes": {
                f"{node['host']}:{node['port']}": node.get("weight", 100)
                for node in _upstream_nodes(upstream)
            },
        }
        if schedule:
            timeout = {}
            for source, target in (
                ("connect_timeout_ms", "connect"),
                ("write_timeout_ms", "send"),
                ("read_timeout_ms", "read"),
            ):
                if source in schedule:
                    timeout[target] = schedule[source] / 1000
            if timeout:
                upstream_item["timeout"] = timeout
        if schedule.get("algorithm") == "least-connections":
            upstream_item["type"] = "least_conn"
        elif schedule.get("algorithm") == "chash":
            upstream_item["hash_on"] = "consumer"
        upstream_items.append(upstream_item)
    upstream_ids = {item["name"]: item["id"] for item in upstream_items}
    routes = []
    for index, route in enumerate(manifest["routes"], start=1):
        tenant = tenants[route["tenant_ref"]]
        auth_plugin = (
            {"jwt-auth": {}}
            if route["auth"]["mode"] == "jwt"
            else {"key-auth": {"hide_credentials": True}}
            if route["auth"]["mode"] == "key-auth"
            else {}
        )
        plugins: dict[str, Any] = {
            **auth_plugin,
            "request-id": {"header_name": "X-Request-ID", "include_in_response": True},
            "proxy-rewrite": {
                "headers": {
                    "add": {
                        "X-AI-Gateway-Tenant": tenant["id"],
                        "X-AI-Gateway-Route": route["id"],
                    }
                }
            },
        }
        if route["auth"]["mode"] != "new-api-token":
            plugins["consumer-restriction"] = {
                "type": "consumer_name",
                "whitelist": [tenant["id"]],
            }
        if route["auth"]["mode"] == "new-api-token":
            plugins["serverless-pre-function"] = {
                "phase": "rewrite",
                "functions": [
                    "return function(conf, ctx)\n"
                    "  local h = ngx.req.get_headers()\n"
                    "  local auth = h['Authorization'] or h['authorization']\n"
                    "  if not auth or auth == '' then\n"
                    "    local key = h['x-api-key'] or h['X-API-Key'] or h['apikey']\n"
                    "    if key and key ~= '' then\n"
                    "      if not key:match('^[Bb]earer%s+') then key = 'Bearer ' .. key end\n"
                    "      ngx.req.set_header('Authorization', key)\n"
                    "    end\n"
                    "  end\n"
                    "  ngx.req.clear_header('x-api-key')\n"
                    "  ngx.req.clear_header('apikey')\n"
                    "end",
                ],
            }
            plugins.pop("consumer-restriction", None)
            plugins["proxy-rewrite"]["headers"]["add"].pop("X-AI-Gateway-Tenant", None)
        if tenant.get("rate_limit_per_minute"):
            plugins["limit-count"] = {
                "count": tenant["rate_limit_per_minute"],
                "time_window": 60,
                "rejected_code": 429,
                "key": "remote_addr" if route["auth"]["mode"] == "new-api-token" else "consumer_name",
                "policy": "local",
            }
            if route["auth"]["mode"] == "new-api-token":
                plugins["limit-count"]["key_type"] = "var"
        if route.get("ai_proxy_multi"):
            ai = route["ai_proxy_multi"]
            instances = []
            for instance in ai["instances"]:
                anthropic = instance["provider"] == "anthropic"
                credential = "${{" + instance["credential_env"] + "}}"
                instances.append({
                    "name": instance["name"],
                    "provider": instance["provider"],
                    "weight": instance.get("weight", 1),
                    "priority": instance.get("priority", 0),
                    "auth": {"header": {"x-api-key" if anthropic else "Authorization": credential if anthropic else "Bearer " + credential}},
                    "options": {"model": instance["model"]},
                    "override": {"endpoint": "${{" + instance["endpoint_env"] + "}}"},
                })
            plugins["ai-proxy-multi"] = {
                "instances": instances,
                "balancer": {"algorithm": "roundrobin"},
                "fallback_strategy": ai.get("fallback_strategy", ["http_429", "http_5xx"]),
                "logging": {"summaries": True, "payloads": False},
            }
        routes.append(
            {
                "id": index,
                "name": route["id"],
                "hosts": route["hosts"],
                "uris": list(dict.fromkeys(
                    path for prefix in route["paths"]
                    for path in ([prefix, prefix.rstrip('/') + '/*'] if '*' not in prefix else [prefix])
                )),
                "status": 1 if tenant["enabled"] else 0,
                "upstream_id": upstream_ids[route["upstream"]],
                "plugins": plugins,
                "labels": {
                    "tenant": tenant["id"],
                    "route": route["id"],
                    # APISIX carries the non-sensitive model contract as
                    # route metadata; New API remains the enforcement point.
                    "allowed_models": ",".join(tenant.get("allowed_models", [])),
                },
            }
        )
    config = {
        "_meta": {"disable_delete": False},
        "consumers": [{"username": tenant["id"]} for tenant in manifest["tenants"]],
        "upstreams": upstream_items,
        "routes": routes,
    }
    runtime = {
        "apisix": {"node_listen": [{"ip": "127.0.0.1", "port": 9080}], "enable_admin": False, "enable_control": False},
        "deployment": {"role": "data_plane", "role_data_plane": {"config_provider": "yaml"}},
    }
    report = {
        "adapter": "apisix",
        "mode": "standalone-file-driven",
        "supported": ["jwt", "key-auth", "host-routing", "uri-routing", "local-rate-limit", "request-id"],
        "scheduling": ["round-robin", "least-connections", "weighted-nodes", "hash-by-consumer"],
        "unsupported_or_external": [
            "postgresql-runtime-config",
            "dynamic-consumer-credential-provisioning",
            "kong-admin-api-semantics",
        ],
        "requires_full_config_publish": True,
        "requires_runtime_credentials": True,
        "upstreams": sorted(upstreams),
    }
    files = {
        "config.yaml": yaml.safe_dump(runtime, sort_keys=False, allow_unicode=True),
        "apisix.yaml": yaml.safe_dump(config, sort_keys=False, allow_unicode=True) + "#END\n",
    }
    return files, report


def render_manifest(manifest: dict[str, Any], adapter: str, output_dir: str | Path) -> dict[str, Any]:
    if adapter not in {"apisix", "caddy"} and any(route.get("ai_proxy_multi") for route in manifest["routes"]):
        raise ValueError("ai_proxy_multi routes require the APISIX renderer")
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    if adapter == "caddy":
        files, report = _render_caddy(manifest)
    elif adapter == "kong":
        files, report = _render_kong(manifest)
    elif adapter == "apisix":
        files, report = _render_apisix(manifest)
    elif adapter == "nginx":
        raise ValueError("nginx adapter is reserved for a later implementation")
    else:
        raise ValueError(f"unsupported adapter: {adapter}")

    for filename, content in files.items():
        (output / filename).write_text(content, encoding="utf-8")
    _write_json(output / "capability-report.json", report)
    return {"output_dir": str(output), "files": sorted([*files, "capability-report.json"]), "report": report}
